### ISSUE TITLE
error: Must contain an `adapter` key referencing the adapter to use.

### ISSUE THREAD

**Issue by PetriHuovinen** [KSDaemon/sails-hook-sequelize#10]
If I leave out the keyword "adapter" from connection configuration, I get the error as described in the title when using the "npm test" command. To clarify the situation, "sails lift" works correctly. This error occurs only when I try to run my tests.

I'm using sails version 0.12.0-rc4

**Comment by duongNA** [comment]
hi, I got the same error. After I reviewed the configuration 1 minute, i realized that i have made mistake in file .sailsrc ( i wrote "hook" instead of "hooks")
Please make sure your .sailsrc is correct.
```
{
  "generators": {
    "modules": {}
  },
  "hooks": {
  	"orm": false,
  	"pubsub": false
  }
}
```

**Comment by PetriHuovinen** [comment]
Thanks, but that wasn't the case here. My .sailsrc is same as yours, @duongNA. I'm still looking for a solution for this.

**Comment by duongNA** [comment]
I guess `npm test` still use hook orm that loads models for waterline. The error message comes from hook orm. I think you should find a way to disable orm when running npm test. Hope it help

**Comment by KSDaemon** [comment]
Hi all! In current version, i can not see such errors. Npm test works as expected. So, closing for now. Feel free to reopen if you find any problems.

**Comment by PetriHuovinen** [comment]
I'm sorry, I should have replied here that it was all my own error. I
didn't use the package correctly first.

6.10.2017 15.04 "Konstantin Burkalev" <notifications@github.com> kirjoitti:
