### ISSUE TITLE
No way to config sequelize logging

### ISSUE THREAD

**Issue by duongNA** [KSDaemon/sails-hook-sequelize#13]
Hi all, I wonder why logging configuration is hard code to `sails.log.verbose` (file index.js)

``` js
if (connection.options == null) {
  connection.options = {};
}
connection.options.logging = sails.log.verbose;
```

It means there is no way to config logging for sequelize

**Comment by duongNA** [comment]
A person had a commit to fix it, I hope it will be merged soon
https://github.com/festo/sails-hook-sequelize/pull/9

**Comment by ruzz311** [comment]
@duong is this still an issue?  Looks like the commit was merged.

**Comment by KSDaemon** [comment]
In current version logging is configurable! Closing.
