### ISSUE TITLE
The hook initializes only the default models connection, even if there are multiple connections defined in config.

### ISSUE THREAD

**Issue by galioy** [KSDaemon/sails-hook-sequelize#21]
I've defined 2 connections in the `/config/connections.js` file:

``` js
      monolithMysql: {
        user: 'store_app',
        database: 'store',
        dialect: 'mysql',
        options: {
          dialect: 'mysql',
          host: 'dockerhost',
          port: 3306,
          logging: console.log
        }
      },

      postgres: {
        user: 'user_app',
        database: 'user_authentication',
        dialect: 'postgres',
        options: {
          dialect: 'postgres',
          host: 'dockerhost',
          port: 8201,
          logging: console.log
        }
      }
```

and in the different models I've put the property `connection`, so that they're distinguished, as follows:

``` js
/**
  * model User
  */
    module.exports = {

      options: {
        connection: 'monolithMysql',
        ...
```

``` js
/**
  * model Token
  */
    module.exports = {

      options: {
        connection: 'postgres',
        ...
```

In `/config/models.js` I set as default connection the `monolithMysql` one. _If I comment out or do not specify the `connection` property in `/config/models.js` then Sequelize hook fails to load._
But that should be overridden by the `connection` property, if specified in the models. 

Nevertheless, when trying to query models that have, eg. `postgres` as connection it still queries them in the MySQL DB, and obviously fails... If I set `postgres` as default connection, then it will always query in the Postgres DB connection, no matter what the local `connection` property of the different models says.

**After some debugging in the module code, I found out that it initializes only 1 instance of Sequelize - an instance with the default connection, specified in `/config/models.js`**

**Dialect:** `mysql` and `postgres`
**Sequelize version:** `^3.21.0`

**Comment by galioy** [comment]
Nevermind. It's not possible atm.
I'm writing an upgrade to support generic initialization of multiple connections.
Gonna make a PR today or tomorrow.

**Comment by galioy** [comment]
Aaand, here's the PR (sorry for the late comment. The PR was actually done the same day. :D )
https://github.com/festo/sails-hook-sequelize/pull/22

**Comment by KSDaemon** [comment]
I think current version supports multiple connections. Please check it out and feel free to reopen!
