### ISSUE TITLE
Working along with waterline

### ISSUE THREAD

**Issue by Crusader4Christ** [KSDaemon/sails-hook-sequelize#31]
I have a big project built on top of Sails/Waterline. Now I need to move from waterline to sequelize. I want to refactor my models one by one, but I can`t use Sequelize hook with default Sails orm enabled, because orm try to initialize Sequelize models too. Need some method for initialization of sequelize models after it was initialized in waterline.

**Comment by KSDaemon** [comment]
Hmm... I can understand your situation, but i can not realize, how to do it. Because you need to initialize only those models, that were not initialized allready with waterline...
May be you can advice some way to do this?

**Comment by Crusader4Christ** [comment]
```
if (!modelDef.options) {
    continue;
}```
before index.js#L110
so only models defined with sequelize options will be loaded

**Comment by KSDaemon** [comment]
Hi! Hmm... Why not?...Also this should be applied later in defining scope and association setup.
I'll try it

**Comment by KSDaemon** [comment]
Well... Of course it is easy to say, rather then do :) 
I've spent a few hours investigating this... What i can say:
* There are definitely more places to check for models and connections type (is it waterline or sequelize). Okay, thats not a big problem.
* What is a big problem, is that you can not tell sails somehow not to migrate sequelize models. So basically, if you set `migrate: 'safe'` — it is ok. But if you set `migrate: 'drop'`, then waterline will try to recreate a table for a model, and of course it can not proceed with sequelize model definitions. And attribute `migrate: 'safe'` can not be set on per model basis.

**Comment by KSDaemon** [comment]
You can check `waterline-and-sequelize` branch and run tests to see a problem

**Comment by Salakar** [comment]
@KSDaemon it is possible to override sails models before it bootstraps them - have done this myself on an internal hook of mine, I've stripped it out from my hook and made an example gist for you:

https://gist.github.com/Salakar/e4bc675cb0f66972875ca5ef2b1b26ce

Tested on sails v1, but the same should apply to older versions hopefully.

**Comment by KSDaemon** [comment]
@Salakar Ou, thanks! I'll have a look!

**Comment by KSDaemon** [comment]
Hi all! Seems to figured out how to make it! Thanks @Salakar for ideas and example.
Will be great, if you can test it
