### ISSUE TITLE
Sails.js v1 support

### ISSUE THREAD

**Issue by mrded** [KSDaemon/sails-hook-sequelize#35]
Hello,

It looks like this module support `0.12` version of sails only.
When will it support `v1`? 

Thanks.

**Comment by KSDaemon** [comment]
Hi @mrded! Well, a have a such plans :)
You're welcome to help with this!

**Comment by mrded** [comment]
Great, I start porting it here https://github.com/mrded/sails-hook-sequelize/tree/sailsjs-v1

**Comment by mrded** [comment]
How do are you thinking to merge it with the main project?

I'm asking because, sails v1 have slightly different location of configuration variables, and if you merge it into the main project - it will break all 0.12 versions.

**Comment by mrded** [comment]
https://github.com/KSDaemon/sails-hook-sequelize/pull/36

**Comment by KSDaemon** [comment]
Well... I think we can continue development in master branch. And in case of bugfixes for Sails@v0.12 we can checkout new branch from last tag (and port bugfix to main code in case if it is relevant too)

**Comment by KSDaemon** [comment]
I've merged #36 :)

**Comment by mrded** [comment]
Fantastic!
