### ISSUE TITLE
how to use pubSub

### ISSUE THREAD

**Issue by baao** [KSDaemon/sails-hook-sequelize#4]
In your sailsrc pubSub hooks are disabled (as they can't be run without the orm hook). Is there a possibility to still use pubSub together with sequelize?

**Comment by festo** [comment]
Unfortunately this limitation is built in Sails.js as you mentioned. I think you need to rewrite the sails-pubsub hook too.

**Comment by diego-vieira** [comment]
looking for the same, it seems someone has started something
https://github.com/ya-kostik/sails-hook-sequelize-pubsub

**Comment by nrempel** [comment]
Take a look at this: https://github.com/AnalogJ/pubsub-emitter/

**Comment by KSDaemon** [comment]
Sails PubSub module is deeply integrated with Waterline ORM, so it's not possible to use it. As @nrempel adviced, you can use any analogue availble. There are tons of them in npm :)
