### ISSUE TITLE
model definitions as Sequelize-Auto

### ISSUE THREAD

**Issue by cadrogui** [KSDaemon/sails-hook-sequelize#48]
Hi, thanks form maintain this repo, its possible that this hook can live with this repo model definition?

https://github.com/sequelize/sequelize-auto

regards, and happy holidays.

**Comment by KSDaemon** [comment]
Hi @cadrogui ! Thanks!
Well, i do not use sequelize-auto tool. But AFAICS, it is not compatible out of the box. 
sequelize-auto uses sequelize.define inside generated model file, but this hook instead just read model properties and options and define model itself.

Happy New Year! Best regards!
