### ISSUE TITLE
Table schema changes are not updating

### ISSUE THREAD

**Issue by mukesh-mohan** [KSDaemon/sails-hook-sequelize#50]
I was trying to update the model, but after re-lifting the sails server, it is not getting updated in the database. Because it was trying to execute the create query instead of update schema even if the table exists also. Please try to suggest an immediate fix.

**Comment by mukesh-mohan** [comment]
Please add a  fix based on this merge for updating the schema alteration https://github.com/sequelize/sequelize/pull/7230 to the following line in the library, which can solve the problem @KSDaemon 

`syncTasks.push(connections[connectionName].sync({ force: forceSync }));` 
currently if alter is enabled in model.js in sails, still it will delete the  tables instead of altering it. because forceSync will be true.

But it should be to `{ force: false, alter: true}`

Thanks.

**Comment by KSDaemon** [comment]
seems to be fixed
