### ISSUE TITLE
sequelize not found in controller

### ISSUE THREAD

**Issue by rogerrw** [KSDaemon/sails-hook-sequelize#51]
When I create a POST request (adding user information from a form), I route that to the corresponding controller, which does the following:

`sequelize.transaction(t => {
      ...
  }
`

at which point fails, sending back a 500 error saying
`error: Sending 500 ("Server Error") response:
 ReferenceError: sequelize is not defined`

**Comment by KSDaemon** [comment]
Hi @rogerrw! Have you exposed sequelize to globals?

**Comment by rogerrw** [comment]
I believe so. My sequelize.js file looks like this:

`
module.exports = {
    hookTimeout: 40000,
    sequelize: {
      exposeToGlobal: true
    }
};
`
