### ISSUE TITLE
Model is not defined.

### ISSUE THREAD

**Issue by devman113** [KSDaemon/sails-hook-sequelize#57]
I followed all instructions.
And I created Post model and tried to retrieve all post records from the db table.
```Post.find()
            .populate("responses")
            .exec(function(err, posts){
                if(err){
                    return res.send(err);
                }
                return res.send(JSON.stringify(posts));
            })```
Cannot read property 'define' of undefined

**Comment by KSDaemon** [comment]
Hi @devman113 Can you provide more details. May be gist or test repo with sails config, model definition, full response processing function.

**Comment by devman113** [comment]
It is fixed. I forked the working sample and it works now. Thanks for your quick response and consideration.
