### ISSUE TITLE
Support Sequelize 5

### ISSUE THREAD

**Issue by kvindasAB** [KSDaemon/sails-hook-sequelize#65]
**Is your feature request related to a problem? Please describe.**
Hello Guys,

First of all, thanks a lot for all the work put into the library. I have been using it for a while, and has been working really great.

**Describe the solution you'd like**
As you may know recently Sequelize 5 was release and I was looking to upgrade, but I would like to confirm if the library will be able to handle it.
Im not completely aware of the code changes in sequelize regarding at least the model definitions, I was quickly looking at least some changes on the TS typings, and saw some usage of Classes which should be great to implement, but at least basic support will be welcome.

Thanks.

**Comment by KSDaemon** [comment]
Hi @kvindasAB! 
I've just updated and refactored tests, and you can see that hook works as expected with latest versions of sails.js and sequelize.js

**Comment by kvindasAB** [comment]
Great to hear that @KSDaemon !!

**Comment by ebaynaud** [comment]
Hi @KSDaemon, is it possible to create a new NPM release so that we don't have to use master in package.json?

**Comment by KSDaemon** [comment]
Hi @ebaynaud ! 
Yep, i'll do my best to publish new version in few days!
