### ISSUE TITLE
Can I set raw: true by default on all queries?

### ISSUE THREAD

**Issue by hoangphuoc25** [KSDaemon/sails-hook-sequelize#7]
I'm running `sails console` and some CRUD operations to test if sequelize is working with `sails`, e.g. `User.findOne({where: {id: myId}}).then(function(result) { console.log(result); })`. I expect the `result` to contain only data retrieved from the db, instead of all data from the promise. I know I can do it by adding `raw: true` to the query but is there anyway to set it by default?

**Comment by joshrickert** [comment]
You should be able to do this by adding `query: {raw: true}` to your connection options. That will be passed into Sequelize during the setup phase. See [this SO thread](http://stackoverflow.com/questions/26228499/setting-all-queries-to-raw-true-sequelize).

Example:
```
  postgresAppDb: {
    user: 'postgres',
    password: '',
    database: 'mydb',
    options: {
      dialect: 'postgres',
      host   : 'localhost',
      port   : 5432,
      logging: true,
      query: {
        raw: true,
      },
    }
  }
```

**Comment by ruzz311** [comment]
@hoangphuoc25 can this be closed?

**Comment by KSDaemon** [comment]
I think, @joshrickert had given answer. So, closing. Feel free to reopen if you have questions.
