### ISSUE TITLE
Support Sequelize 6

### ISSUE THREAD

**Issue by ebaynaud** [KSDaemon/sails-hook-sequelize#80]
Any plan to support Sequelize 6? Sequelize 7 is in preparation 🤓

**Comment by KSDaemon** [comment]
Seems that current tests don't break for sequelize v6 :) that's great!

**Comment by KevinND** [comment]
Hello @KSDaemon,
The latest release still [uses the `continuation-local-storage` package](https://github.com/KSDaemon/sails-hook-sequelize/blob/v2.0.0/index.js#L18C34-L18C71), although [Sequelize v6 requires using the `cls-hooked` package](https://sequelize.org/docs/v6/other-topics/upgrade/#cls).

There is a [commit with the right package](https://github.com/KSDaemon/sails-hook-sequelize/commit/25f8786f4b3e9ebf2986ed30cb3560c5cd0188b7) which has been merged into `master`, but it hasn't been included in v2.0.0.
Can you create a release including this commit please?

**Comment by KSDaemon** [comment]
Sure! thnx for pinging! Done! Published v2.0.1

**Comment by KSDaemon** [comment]
So I think we can close this one as done :) 
Feel free to reopen if I am wrong.
