### ISSUE TITLE
Other fields not accessible for custom validations

### ISSUE THREAD

**Issue by micodls** [KSDaemon/sails-hook-sequelize#93]
I'm trying to create a custom validation like so.

```
module.exports = {
    attributes : {
        startDate : {
            field     : 'start_date',
            type      : 'DATETIME',
            allowNull : false,
            validate  : {
                isValid : async (value) => {
                    sails.log.info(this.endDate);
                },
            },
        },
        endDate : {
            field     : 'end_date',
            type      : 'DATETIME',
            allowNull : false,
            validate  : {
                isValid : async (value) => {
                    // Do something
                },
            },
        },
    },
    associations : function() {},
    defaultScope : function() {},
    options      : {
        tableName       : 'campaigns',
        classMethods    : {},
        instanceMethods : {},
        validate : {
            isStartDateValid : () => {
                console.log(this.startDate); // prints undefined
            },
        },
        scopes : {},
    },
};
```

Is there a way to access other fields inside custom validations like the samples here: https://sequelize.org/docs/v6/core-concepts/validations-and-constraints/#per-attribute-validations

**Expected behavior**
Should be able to access other fields for custom validations

**Desktop (please complete the following information):**
 - OS: Mac
 - Node.js version: 18.12.1
 - Sails version: 1.5.3
 - Sails-hook-sequelize version: 2.0.0

**Comment by KSDaemon** [comment]
Hi @micodls Well, first of all — your example is not the same as in the docs :) 
And second: have a look at model-wide validations. I think it is a better place to make checks that involve multiple attributes. See https://sequelize.org/docs/v6/core-concepts/validations-and-constraints/#model-wide-validations

**Comment by KSDaemon** [comment]
Please try this one:
```javascript
module.exports = {
    ...
    options      : {
        tableName       : 'campaigns',
        classMethods    : {},
        instanceMethods : {},
        validate : {
            isStartDateValid() {
                console.log(this); // prints {}
                console.log(this.startDate); // prints undefined
            },
        },
        scopes : {},
    },
};
```

**Comment by micodls** [comment]
Thanks @KSDaemon! That one works 😄

**Comment by KSDaemon** [comment]
@micodls Pay more attention to how arrow functions in JS work and how they capture `this` ;)
